/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/models/TheGallery.glb 
*/
import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useGLTF,} from '@react-three/drei'
import { useNavigate } from 'react-router-dom'
import { useFrame} from '@react-three/fiber'
 

export function Gallery(props) {
    const { nodes, materials } = useGLTF('./models/TheGallery.glb')
    const navigate = useNavigate()
    const [active, setActive] = useState(true)
    const [initialPosition, setInitialPosition] = useState([-10, -10.45, -3])
    const [initialRotation, setInitialRotation] = useState([0, -1.575, -0.02])

    const handleClick = (route) => {
        setActive(!active)
        // Navigate to the AboutMe component when the mesh is clicked
        navigate(route)
    }
    const group = useRef()

    const handleReset = () => {
        // Reset position and rotation to their initial values
        setInitialPosition([-11, -10.45, -3])
        setInitialRotation([0, -1.575, -0.02])
    }


    useFrame((state) => {
      const t = state.clock.getElapsedTime();
    
      // Adjust the animated values to be close to the initial values
      
      group.current.rotation.y = THREE.MathUtils.lerp(
        group.current.rotation.y,
        Math.sin(t / 3) / 15 + initialRotation[1],
        0.1
      );
      group.current.rotation.z = THREE.MathUtils.lerp(
        group.current.rotation.z,
        Math.sin(t / 2) / 15 + initialRotation[2],
        0.3
      );
      group.current.position.y = THREE.MathUtils.lerp(
        group.current.position.y,
        (-2 + Math.sin(t / 3)) / 2 + initialPosition[1],
        0.1
      );
    });

    const [hovered, setHovered] = useState(false)

    useEffect(() => {
        
        document.body.style.cursor = hovered ? 'pointer' : 'auto'
      }, [hovered])

    return (
        <>
            {/* Add a button to reset position and rotation */}
            <group ref={group} {...props} dispose={null} position={initialPosition} rotation={initialRotation}>
                <group>
                    <mesh
                        geometry={nodes.FRONT_SHELL.geometry}
                        material={materials['basicConsoleColorA.001']}
                        position={[1.709, 8.366, -4.298]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 8.366, -4.298]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 8.366, -4.298]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube017_1.geometry} material={materials.basicConsoleColorA} />
                        <mesh geometry={nodes.Cube017_2.geometry} material={materials.basicConsoleColorA} />
                    </group>
                    {/* RED ABOUT ME  */}
                    <mesh
                        geometry={nodes.screen.geometry}
                        material={materials.ABOUTME}
                        position={[2.026, 8.615, -4.349]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.054, 1.074, 1.132]}
                        onClick={() => handleClick('/about')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} />
                    
                    <mesh
                        geometry={nodes.screen_border.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -4.349]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -4.349]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube013.geometry}
                        material={materials.basicConsoleColorA}
                        position={[1.971, 8.486, -6.02]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube014.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -6.02]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube015.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -6.02]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube016.geometry}
                        material={materials.basicConsoleColorA}
                        position={[1.971, 8.486, -6.02]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube017.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 8.595, -2.506]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube018.geometry}
                        material={materials.basicConsoleColorA}
                        position={[2.014, 8.595, -2.506]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder004.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 7.928, -6.023]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder005.geometry}
                        material={materials.basicConsoleColorA}
                        position={[1.996, 7.929, -6.024]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle.geometry}
                        material={materials.POWER}
                        position={[2.044, 9.245, -3.169]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME.geometry}
                        material={nodes.FULL_NAME.material}
                        position={[2.016, 7.721, -4.059]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START001.geometry}
                        material={materials.TEXT}
                        position={[1.972, 7.749, -6.029]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT001.geometry}
                        material={materials.TEXT}
                        position={[1.978, 7.749, -2.548]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.FRONT_SHELL001.geometry}
                        material={materials['ORANGES.001']}
                        position={[1.709, 12.343, -4.298]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL001.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 12.343, -4.298]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 12.343, -4.298]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube006_2.geometry} material={materials.ORANGES} />
                        <mesh geometry={nodes.Cube006_3.geometry} material={materials.ORANGES} />
                    </group>
                    {/* ORANGE SKILLS */}
                    <mesh
                        geometry={nodes.screen001.geometry}
                        material={materials.SKILLS}
                        position={[1.986, 12.565, -4.309]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.163, 1.186, 1.25]}
                        onClick={() => handleClick('/skills')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} 
                    />
                    <mesh
                        geometry={nodes.screen_border001.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.592, -4.349]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge001.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.592, -4.349]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube001.geometry}
                        material={materials.ORANGES}
                        position={[1.971, 12.463, -6.02]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube002.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.463, -6.02]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube003.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.463, -6.02]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube004.geometry}
                        material={materials.ORANGES}
                        position={[1.971, 12.463, -6.02]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube005.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 12.572, -2.506]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube006.geometry}
                        material={materials.ORANGES}
                        position={[2.014, 12.572, -2.506]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder001.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 11.906, -6.023]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder002.geometry}
                        material={materials.ORANGES}
                        position={[1.996, 11.906, -6.024]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle001.geometry}
                        material={materials.POWER}
                        position={[2.044, 13.222, -3.169]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME001.geometry}
                        material={nodes.FULL_NAME001.material}
                        position={[2.016, 11.698, -4.059]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START002.geometry}
                        material={materials.TEXT}
                        position={[1.972, 11.726, -6.029]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT002.geometry}
                        material={materials.TEXT}
                        position={[1.978, 11.726, -2.548]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.FRONT_SHELL002.geometry}
                        material={materials['YELLOW.001']}
                        position={[1.709, 8.366, -9.782]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL002.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 8.366, -9.782]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 8.366, -9.782]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube013_1.geometry} material={materials.YELLOW} />
                        <mesh geometry={nodes.Cube013_2.geometry} material={materials.YELLOW} />
                    </group>
                    {/* YELLOW PORTFOLIO */}
                    <mesh
                        geometry={nodes.screen002.geometry}
                        material={materials.PORTFOLIO}
                        position={[2.026, 8.615, -9.833]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.054, 1.074, 1.132]}
                        onClick={() => handleClick('/portfolio')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} 
                    />
                    <mesh
                        geometry={nodes.screen_border002.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -9.833]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge002.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -9.833]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube007.geometry}
                        material={materials.YELLOW}
                        position={[1.971, 8.486, -11.503]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube008.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -11.503]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube009.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -11.503]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube010.geometry}
                        material={materials.YELLOW}
                        position={[1.971, 8.486, -11.503]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube011.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 8.595, -7.99]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube012.geometry}
                        material={materials.YELLOW}
                        position={[2.014, 8.595, -7.99]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder003.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 7.928, -11.506]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder006.geometry}
                        material={materials.YELLOW}
                        position={[1.996, 7.929, -11.508]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle002.geometry}
                        material={materials.POWER}
                        position={[2.044, 9.245, -8.653]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME002.geometry}
                        material={nodes.FULL_NAME002.material}
                        position={[2.016, 7.721, -9.543]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START003.geometry}
                        material={materials.TEXT}
                        position={[1.972, 7.749, -11.513]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT003.geometry}
                        material={materials.TEXT}
                        position={[1.978, 7.749, -8.032]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.FRONT_SHELL003.geometry}
                        material={materials['GREEN.001']}
                        position={[1.709, 12.366, -9.782]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL003.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 12.366, -9.782]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 12.366, -9.782]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube021_1.geometry} material={materials.GREEN} />
                        <mesh geometry={nodes.Cube021_2.geometry} material={materials.GREEN} />
                    </group>
                    {/* GREEN RESUME */}
                    <mesh
                        geometry={nodes.screen003.geometry}
                        material={materials.RESUME}
                        position={[2.026, 12.615, -9.833]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.054, 1.074, 1.132]}
                        onClick={() => handleClick('/resume')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} 
                    />
                    <mesh
                        geometry={nodes.screen_border003.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.615, -9.833]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge003.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.615, -9.833]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube019.geometry}
                        material={materials.GREEN}
                        position={[1.971, 12.486, -11.503]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube020.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.486, -11.503]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube021.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.486, -11.503]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube022.geometry}
                        material={materials.GREEN}
                        position={[1.971, 12.486, -11.503]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube023.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 12.595, -7.99]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube024.geometry}
                        material={materials.GREEN}
                        position={[2.014, 12.595, -7.99]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder007.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 11.928, -11.506]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder008.geometry}
                        material={materials.GREEN}
                        position={[1.996, 11.929, -11.508]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle003.geometry}
                        material={materials.POWER}
                        position={[2.044, 13.245, -8.653]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME003.geometry}
                        material={nodes.FULL_NAME003.material}
                        position={[2.016, 11.72, -9.543]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START004.geometry}
                        material={materials.TEXT}
                        position={[1.972, 11.749, -11.513]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT004.geometry}
                        material={materials.TEXT}
                        position={[1.978, 11.749, -8.032]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.FRONT_SHELL004.geometry}
                        material={materials['BLUE.001']}
                        position={[1.709, 8.366, -15.458]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL004.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 8.366, -15.458]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 8.366, -15.458]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube027_1.geometry} material={materials.BLUE} />
                        <mesh geometry={nodes.Cube027_2.geometry} material={materials.BLUE} />
                    </group>
                    {/* BLUE CONNECTIONS */}
                    <mesh
                        geometry={nodes.screen005.geometry}
                        material={materials['CONNECTIONS.001']}
                        position={[1.988, 8.615, -15.509]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.14, 1.163, 1.226]}
                        onClick={() => handleClick('/connections')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} 
                    />
                    <mesh
                        geometry={nodes.screen004.geometry}
                        material={materials.CONNECTIONS}
                        position={[1.988, 8.615, -15.509]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.14, 1.163, 1.226]}
                    />
                    <mesh
                        geometry={nodes.screen_border004.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -15.509]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge004.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 8.615, -15.509]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube025.geometry}
                        material={materials.BLUE}
                        position={[1.971, 8.486, -17.18]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube026.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -17.18]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube027.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 8.486, -17.18]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube028.geometry}
                        material={materials.BLUE}
                        position={[1.971, 8.486, -17.18]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube029.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 8.595, -13.666]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube030.geometry}
                        material={materials.BLUE}
                        position={[2.014, 8.595, -13.666]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder009.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 7.928, -17.183]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder010.geometry}
                        material={materials.BLUE}
                        position={[1.996, 7.929, -17.184]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle004.geometry}
                        material={materials.POWER}
                        position={[2.044, 9.245, -14.329]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME004.geometry}
                        material={nodes.FULL_NAME004.material}
                        position={[2.016, 7.721, -15.219]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START005.geometry}
                        material={materials.TEXT}
                        position={[1.972, 7.749, -17.189]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT005.geometry}
                        material={materials.TEXT}
                        position={[1.978, 7.749, -13.708]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.FRONT_SHELL005.geometry}
                        material={materials['PURPLE.001']}
                        position={[1.709, 12.366, -15.518]}
                        scale={[1, 0.9, 1]}
                    />
                    <mesh
                        geometry={nodes.BACK_SHELL005.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.709, 12.366, -15.518]}
                        scale={[1, 0.9, 1]}
                    />
                    <group position={[1.709, 12.366, -15.518]} scale={[1, 0.9, 1]}>
                        <mesh geometry={nodes.Cube045.geometry} material={materials['PURPLE.002']} />
                        <mesh geometry={nodes.Cube045_1.geometry} material={materials['PURPLE.002']} />
                    </group>
                    {/* PURPLE CONTACT ME */}
                    <mesh
                        geometry={nodes.screen006.geometry}
                        material={materials['CONTACT ME']}
                        position={[2.026, 12.615, -15.57]}
                        rotation={[-Math.PI, 0, Math.PI / 2]}
                        scale={[1.054, 1.074, 1.132]}
                        onClick={() => handleClick('/contact')}
                        onPointerOver={() => setHovered(true)}
                        onPointerOut={() => setHovered(false)} 
                    />
                    <mesh
                        geometry={nodes.screen_border005.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.615, -15.57]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.screen_edge005.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.015, 12.615, -15.57]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={[1.044, 1.065, 1.122]}
                    />
                    <mesh
                        geometry={nodes.Cube031.geometry}
                        material={materials['PURPLE.002']}
                        position={[1.971, 12.486, -17.24]}
                        rotation={[-1.504, 0, 0]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube032.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.486, -17.24]}
                        rotation={[-1.504, 0, 0]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube033.geometry}
                        material={materials.ConsoleColorA}
                        position={[1.963, 12.486, -17.24]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube034.geometry}
                        material={materials['PURPLE.002']}
                        position={[1.971, 12.486, -17.24]}
                        scale={[0.045, 0.11, 0.11]}
                    />
                    <mesh
                        geometry={nodes.Cube035.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.011, 12.595, -13.727]}
                        scale={0.999}
                    />
                    <mesh
                        geometry={nodes.Cube036.geometry}
                        material={materials['PURPLE.002']}
                        position={[2.014, 12.595, -13.727]}
                        scale={[0.917, 0.953, 0.953]}
                    />
                    <mesh
                        geometry={nodes.Cylinder011.geometry}
                        material={materials.ConsoleColorA}
                        position={[2.001, 11.928, -17.243]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.074}
                    />
                    <mesh
                        geometry={nodes.Cylinder012.geometry}
                        material={materials['PURPLE.002']}
                        position={[1.996, 11.929, -17.245]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.07}
                    />
                    <mesh
                        geometry={nodes.Circle005.geometry}
                        material={materials.POWER}
                        position={[2.044, 13.245, -14.39]}
                        rotation={[0, 0, -Math.PI / 2]}
                        scale={0.038}
                    />
                    <mesh
                        geometry={nodes.FULL_NAME005.geometry}
                        material={nodes.FULL_NAME005.material}
                        position={[2.016, 11.72, -15.28]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.116}
                    />
                    <mesh
                        geometry={nodes.START006.geometry}
                        material={materials.TEXT}
                        position={[1.972, 11.749, -17.25]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                    <mesh
                        geometry={nodes.SELECT006.geometry}
                        material={materials.TEXT}
                        position={[1.978, 11.749, -13.768]}
                        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                        scale={0.171}
                    />
                </group>
            </group>
        </>
    )
}

useGLTF.preload('./models/TheGallery.glb')
